name: exachanger_get_app
description: "A new Flutter project."
publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: ^3.8.0

dependencies:
  animated_bottom_navigation_bar: ^1.4.0
  animations: ^2.0.11
  cached_network_image: ^3.4.1
  connectivity_plus: ^6.0.5
  cupertino_icons: ^1.0.8
  dio: ^5.8.0+1
  flutter:
    sdk: flutter
  flutter_spinkit: ^5.2.1
  flutter_svg: ^2.1.0
  fluttertoast: ^8.2.12
  font_awesome_flutter: ^10.8.0
  get: ^4.7.2
  image_picker: ^1.0.7
  intl: ^0.20.2
  intl_phone_field: ^3.2.0
  loading_animations: ^2.2.0
  logger: ^2.5.0
  lottie: ^3.3.1
  package_info_plus: ^8.3.0
  pretty_dio_logger: ^1.4.0
  pull_to_refresh: ^2.0.0
  shared_preferences: ^2.5.3
  shimmer: ^3.0.0
  flutter_html: ^3.0.0-beta.2
  url_launcher: ^6.2.5
  http: ^1.2.1

dev_dependencies:
  flutter_lints: ^6.0.0
  flutter_test:
    sdk: flutter
  change_app_package_name: ^1.5.0


flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/lottie/
